name: Build Android App

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install SWIG
        run: |
          sudo apt-get update
          sudo apt-get install -y swig
          swig -version

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 27
          build-tools: 27.0.3
          ndk-version: "21.4.7075529"

      - name: Install CMake
        run: |
          sudo apt-get install -y cmake
          cmake --version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (Debug)
        run: ./gradlew assembleDebug
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Build with Gradle (Release without signing)
        run: ./gradlew assembleRelease
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        continue-on-error: true

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: main/build/outputs/apk/*/debug/*.apk

      - name: Upload Release APK (if built)
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: release-apk
          path: main/build/outputs/apk/*/release/*.apk

      - name: Run Tests
        run: ./gradlew test
        continue-on-error: true

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: main/build/reports/tests/
